# in this notebook, we're going tp cover some of the most practical fundamental concepts of tensor using TensorFloW

More specifically, we're going to cover:
* Intruduction to tensors
* Getting to tensors
* Maniuplate the tensors
* Tensors , NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with Tenserflow (or TOUs)
* Exersises to try yourself!

## Intrudution to Tensors

In [ ]:
# Import TenserFlow & Check the version
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# Create tensors with tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the nummber of dimentions of a tensor (ndim stands for number of dimentions)
scaler.ndim

0

In [ ]:
# Create a Vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimention of out vector
vector.ndim

1

In [ ]:
# Create a metrix (has more than 1 dimetion)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Checking the numebr of dimentions of our matrix
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant( [[10., 7.],
                              [3., 2.],
                               [8., 9.]], dtype = tf.float16 ) # Specify the data type with dtype parameter
                               # The tf.float set a particular data type and that's cause the higher the bit of the precisior the
                               # more accurate will the number be stored on the storage
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# What do you think the number of dimentions are in another_matrix?
another_matrix.ndim, another_matrix.shape

(2, TensorShape([3, 2]))

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6],
                      [7, 8, 9]],
                      [[10, 11, 12],
                      [13, 14, 15],
                      [16, 16, 17]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 16, 17]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:
* Scaler : a single number
* Vector : a number with direction (e.g. wind speed and direction)
* Matrix : a 2-dimentional array of numbers
* Tensor : an n-dimensional array of numbers (when n can be any number, a 0-dimentinal tensoe is a scalar, a 1-dimontioanl tensor is a vector)

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

### Creating tensors with tf.Variable

In [ ]:
# Create the same Tensor with tf.Variable() as above
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try cahnge one of the elements in our changanle tensor
changable_tensor[0] = 7
changable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign()
changable_tensor[0].assign(7)
changable_tensor

In [ ]:
# Let's try to change our unchangable_tensor
unchangable_tensor[0] = 7

In [ ]:
unchangable_tensor[0].assign(7)

🔑Note: Rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors, as TensorFlow does this for you. However, if in doubt, use tf.constant and change it later if needed.

### Creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers.

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape= (3, 2)) # normal for normal distubrution
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
tf.random.set_seed(42)

random_bezan = tf.random.uniform(shape= (3, 4), minval = 0, maxval=10)
print(tf.reduce_mean(random_bezan, axis=1))

tf.Tensor([4.807335 5.827237 3.705618], shape=(3,), dtype=float32)


### Shuffle a tensor (valuable for you want to shuffle youre data so the inherent order doesn't effect learning )

In [ ]:
random_bezan

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[6.6456213 , 4.4100676 , 3.528825  , 4.6448255 ],
       [0.33660412, 6.8467236 , 7.4011745 , 8.724445  ],
       [2.2632635 , 2.2319686 , 3.103881  , 7.223358  ]], dtype=float32)>

In [ ]:
not_shuffled = tf.random.Generator.from_seed(42)
not_shuffled = tf.random.uniform(shape=(3, 2), dtype=tf.int32, maxval=100, minval=0)

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[98, 43],
       [19, 94],
       [32, 13]], dtype=int32)>

In [ ]:
# shuffle our  non shuffled tensor
tf.random.set_seed(42)
shuffled =  tf.random.shuffle(not_shuffled ,seed=0)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[32, 13],
       [98, 43],
       [19, 94]], dtype=int32)>

🛠️ **Exercise: ** Read through TensorFlow doumentation on randome seed generator and practice writing 5 random seeds and shuffle them.
It looks like we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed:
> Rull 4: "If both the flobal and the operation seed are set Both seeds are used in conjuction to determine the random sequence"


In [ ]:
tf.random.set_seed(42) # Global level random seed
tf.random.shuffle(not_shuffled, seed=(42)) # Operation level random seed

import random
for i in range(10):
  print(*range(1, 10, 3))

### Other ways to make tensors:


#### NumPy ones
Since NumPy tensors are the same as the TensorFlow tensors we can be using numpy finction in TensorFlow

In [ ]:
tf.ones(shape= (10, 7))

#### NumPy Zeros

In [ ]:
tf.zeros(shape=(10, 7))


#### NumPy linspace, eye

In [ ]:
tf.linspace(1, 10 ,10)

In [ ]:
tf.eye(5, 5)

### Turn NumPy arrays into tensors
The main deifference between NumPy arrays and Tensorflos tensors is that tensors can by run on the GPU computing.

In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # Create a NumPy array between 1 and 25
numpy_A

# x = tf.constant(some_matrix) # capital for Matrix or tensor
# y = tf.constant(vector) # non-capital for vector

In [ ]:
A = tf.constant(numpy_A)
A, type(A), type(numpy_A)

In [ ]:
B = tf.constant(numpy_A, shape=(2, 3, 4))
B

In [ ]:
 A = tf.constant(numpy_A, shape=(3, 8))
 A

In [ ]:
tf.random.set_seed(42)
a = tf.random.uniform(shape=(2, 5), minval=0, maxval=10, dtype=tf.int32)
a

In [ ]:
b = tf.constant(a, shape=(5, 2))
b

### Getting information from tensors
When dealing with tensoes you probably want to be aware of the fallowing attributes:
* Shape
* Rank
* Axis or dimention
* Size

In [ ]:
# Create a rank 4 tensor (4 dimentions)
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
2 * 3 * 4 * 5

In [ ]:
# Get various attributes of our tensor
def tensor_info(tensors_name):
  """
  Getting some info from the tensor
  dtype, ndim, shape, first and last index of the shape, size

  """
  print("Data type pf every element: ", tensors_name.dtype)
  print("Number of dimensions (rank): ", tensors_name.ndim)
  print("Shape of tensor: ", tensors_name.shape)
  print("Elements along the 0 axis: ", tensors_name.shape[0])
  print("Elemetns along the last axis: ", tensors_name.shape[-1])
  print("Total number of elements in our tensor: ", tf.size(tensors_name).numpy()) # ADDING the .numpy() is for getting the number only

In [ ]:
tensor_info(rank_4_tensor)

In [ ]:
tf.random.set_seed(42)
rank_4_random = tf.random.uniform(minval=1, maxval=100, shape=(2, 3, 4, 5), dtype=tf.int32)
rank_4_random


### Indexing tensors

Tensors can be indexed just like Python lists.


In [ ]:
# Get the first 2 elements of each dimension
rank_4_random[:2, :2, :2, :2]

In [ ]:
# Get the first element of each dimention of each index except the final one
rank_4_random[:1, :1, :1, :]

In [ ]:
rank_4_tensor.shape

In [ ]:
rank_4_random[:1, :1, :, :1]

In [ ]:
rank_4_random

In [ ]:
rank_4_random[:, :, :1, :1]

In [ ]:
# Create a rank 2 tensor:
tf.random.set_seed(42)
rank_2_tensor = tf.random.uniform(minval=1, maxval=100, shape=(2, 2), dtype = tf.int32)
rank_2_tensor

In [ ]:
tensor_info(rank_2_tensor)

In [ ]:
# Create a list
some_list = [1, 2, 3, 4]

In [ ]:
# Get the last item of each of our rank 2 tensor and the list
rank_2_tensor[:, -1], some_list[-1]

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # (...) means all the axis before the new axis
rank_3_tensor

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis= -1) # "-1" means expand the final axis if the first one is what you want you should do axis = 0

In [ ]:
tf.expand_dims(rank_2_tensor, axis= 0)

In [ ]:
rank_2_tensor

## Maniopulate Tensors (tensor operations)

**Basic operation**
`+`, `-`, `*`, `/`

In [ ]:
 # You can add values to a tensor using the addition operator
 tensor = tf.constant([[10, 7], [3, 4]])
 tensor + 10

In [ ]:
# Original tensor is unchanged
tensor

In [ ]:
# In order to change it we have to do as so:
tensor += 10 # tensor = tensor + 10
tensor

In [ ]:
# Multiplication also works
tensor * 10

In [ ]:
# Subtraction if you want to
tensor - 10

In [ ]:
# Division maybe
tensor / 10

In [ ]:
# We can use the tenserflow built_in function:
tf.multiply(tensor, 10)

### \**Matirix multiplication**

In machine leanring, matrix multiplication is one of the most common tensor operations

There are two rules that our tensors (or matrices) need to fulfil if we're going to matrix multiply them:

1. The inner dimension must match
2. The resulting matrix has the shape of the outer dimension

In [ ]:
# Matrix multiplication in tenserflow
print(tensor)
tf.linalg.matmul(tensor, tensor) # dot_product multiplication

In [ ]:
tensor * tensor # Normal mulrtiplication

In [ ]:
# Let's make 2 tensors and make a dot_product multiplication
a = tf.constant([1, 2, 5, 7 ,2 ,1 ,3, 3, 3], shape=(3, 3))
b = tf.constant([3, 5, 6, 7, 1 ,8], shape=(3 ,2))
tf.matmul(a, b)

In [ ]:
# identiry matrix
def identity_matrix_checker(name):
  if tf.reduce_all(name @ name == name):
    print("Yeah")
  else:
    print("No")


identity_matrix_checker(tf.constant([[2, -3, -5],[-1, 4, 5],[1, -3, -4]]))

In [ ]:
# Matrix multiplication with Python operator "@" (for the dot_production)
tensor @ tensor

In [ ]:
tensor.shape

In [ ]:
# Create a tensor of (3, 2)
tf.random.set_seed(42)
X = tf.random.uniform(minval=1, maxval=10, shape=(3, 2), dtype=tf.int32)

# Create another (3, 2) tensor
y = tf.random.uniform(minval=1, maxval=10, shape=(3, 2), dtype=tf.int32)

X, y

In [ ]:
# Try to matrix multiply tensors of same shape
tf.matmul(X, y)

In [ ]:
# using the reshape method
X_2 = tf.reshape(X, shape=(2, 3))
X_2

In [ ]:
X_2 @ y

In [ ]:
# Using the transpose method
tf.transpose(X), tf.reshape(X, shape=(2, 3)), X

In [ ]:
# The answewr of the matrix multiplication of reshape and transpose methods arn't the same
tf.matmul(tf.transpose(X), y) == tf.matmul(tf.reshape(X , shape=(2, 3)), y)

That's cause the transpose just flip the martix insted of reshaping it

**The Dot Product**

The matrix multiplication is also referred as the dot product.

you can perform matrix multiplication using:

*`tf.matmul()`

*`tf.tensordot()`

*`@`

In [ ]:
X, y

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), y, axes=1)


In [ ]:
# Perform matrix m|ultiplication between X and y (transposed)
tf.matmul(X, tf.transpose(y))

In [ ]:
# Perform matrix multiplication between X and y reshape
tf.matmul(X, tf.reshape(y, shape=(2, 3)))

In [ ]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y: ")
print(y, "\n")

print("Y reshaped to (2, 3): ")
print(tf.reshape(y, shape=(2, 3)), "\n")

print("Y transposed: ")
print(tf.transpose(y))

In [ ]:
tf.matmul(X, tf.transpose(y))

Generally, when performing matrix multiplication on two tensors and on of the axes doesn't line up, you'll
transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules.

In [ ]:
### Changing the datatype of a tensor

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

In [ ]:
C = tf.constant([7, 10])
C.dtype

In [ ]:
# change from float 32 to float64
B = tf.cast(B, dtype=tf.float16)
B, B.dtype

In [ ]:
# Change the dtype from float32 to int32
E = tf.cast(C, dtype=tf.float32)
E

# Aggregating tensors
Aggregting tensors = condencing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
D = tf.constant([-7, -10])
D

In [ ]:
# Get the absolute values
tf.abs(D)

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size= 50))
E

In [ ]:
tf.size(E), E.shape, E.ndim

In [ ]:
# Find the minimum
tf.reduce_min(E)

In [ ]:
# Find the maximum
tf.reduce_max(E)

In [ ]:
# Find the mean
tf.reduce_mean(E)

In [ ]:
# Find the sum of a tensor
tf.reduce_sum(E)

🛠️**Exercise:** With what We've just learned, find the variance and standard deviation of out `E` tensor usign tensorflow methods.

In [ ]:
# Find the variance of a tensor
tf.math.reduce_variance(E) # Won't work...

In [ ]:
# To find the variance of our tensor we need access to tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

In [ ]:
# Find the standard deviation
tf.math.reduce_std(E)

In [ ]:
# Complex the tensor
E = tf.cast(E, dtype=tf.complex64)

In [ ]:
tf.math.reduce_std(E)

In [ ]:
# Find the variance of our E tensor
tf.math.reduce_variance(E)

### Find the positional maximum and minimum


In [ ]:
# Create a new tensor for finding the positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

In [ ]:
# To find the positional maximum
tf.argmax(F)

In [ ]:
# Index on our largest value:
F[tf.argmax(F)]

In [ ]:
# Find the max value of F
tf.reduce_max(F)

In [ ]:
# Find the inecies of a tensor
tf.random.set_seed(42)
M = tf.random.uniform(shape=(3, 4), minval= 1, maxval = 10, dtype=tf.int32)
tf.where(tf.equal(M, 8))

tf.where(M == 8)

In [ ]:
# Check the equality
assert F[tf.argmax(F)] == tf.reduce_max(F) # assert will cause an error if the they arn't equal

In [ ]:
# Find the positional minimum
tf.argmin(F)

In [ ]:
# Find the minimum using the positional minimum index
F[16]

### Squeezing a tensor (Removing all single dimension)

In [ ]:
# Create a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

In [ ]:
G.shape

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

In [ ]:
# This by numpy also does the same thing
g = np.array(G)
g.flatten()

### One-hot encoding  

In [ ]:
# Create a list of indices
some_list = [0 ,1 ,2 ,3] # could be red, green, blue, purple

# One-hot encode our list of indices
tf.one_hot(some_list, depth=4)

In [ ]:
# Specifu custom values for one-hot endcoding
tf.one_hot(some_list, depth=4, on_value="yo i love deep learning", off_value="I also like to dance")

### Squaring , log, square root

In [ ]:
# Create a new tensor
H = tf.range(1, 10)

In [ ]:
# Square it
tf.square(H)

In [ ]:
# Find the square root (Will error, method require non-int type)
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

In [ ]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

### Tensors and numpy

Tensorflow intracts beautifully with NumPy arrays

🔑Note: One of the main differeces between a TensorFlow and a NumPy array is that a TensorFlow tensor can run on both GPU and TPU.

In [ ]:
# Create a tensor directly from a NumPy tensor
J = tf.constant(np.array([3., 7., 10.]))
J

In [ ]:
# Convert our tensor back to NumPy array
np.array(J), type(np.array(J))

In [ ]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

In [ ]:
# The deafault types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10])

# Check the datatype of each
numpy_J.dtype, tensor_J.dtype

### Finding acces to GPUs

In [ ]:
tf.config.list_physical_devices()

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found
